<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="17"
            tests="1">

  <testsuite name="challenge"
    errors="0" failures="17" hostname="" id="" package="challenge" skipped="0"
    tests="1" time="23.99" timestamp="">
  
    <testcase name="test" classname="challenge" time="23.99" assertions="17">  <failure message="Testing if element &lt;(//input)[1]&gt; contains text: &#34;1&#34; in 1000 ms. - expected [0;32m&#34;1&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:12:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[2]&gt; contains text: &#34;2&#34; in 1000 ms. - expected [0;32m&#34;2&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:17:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[3]&gt; contains text: &#34;3&#34; in 1000 ms. - expected [0;32m&#34;3&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:22:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[4]&gt; contains text: &#34;4&#34; in 1000 ms. - expected [0;32m&#34;4&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:27:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[5]&gt; contains text: &#34;5&#34; in 1000 ms. - expected [0;32m&#34;5&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:32:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[6]&gt; contains text: &#34;6&#34; in 1000 ms. - expected [0;32m&#34;6&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:37:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[7]&gt; contains text: &#34;7&#34; in 1000 ms. - expected [0;32m&#34;7&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:42:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[8]&gt; contains text: &#34;8&#34; in 1000 ms. - expected [0;32m&#34;8&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:47:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[9]&gt; contains text: &#34;9&#34; in 1000 ms. - expected [0;32m&#34;9&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:52:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[10]&gt; contains text: &#34;10&#34; in 1000 ms. - expected [0;32m&#34;10&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:57:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[11]&gt; contains text: &#34;11&#34; in 1000 ms. - expected [0;32m&#34;11&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:62:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[12]&gt; contains text: &#34;12&#34; in 1000 ms. - expected [0;32m&#34;12&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:67:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[13]&gt; contains text: &#34;13&#34; in 1000 ms. - expected [0;32m&#34;13&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:72:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[14]&gt; contains text: &#34;14&#34; in 1000 ms. - expected [0;32m&#34;14&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:77:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[15]&gt; contains text: &#34;15&#34; in 1000 ms. - expected [0;32m&#34;15&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:82:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[16]&gt; contains text: &#34;16&#34; in 1000 ms. - expected [0;32m&#34;16&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:87:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

      <failure message="Testing if element &lt;(//input)[17]&gt; contains text: &#34;17&#34; in 1000 ms. - expected [0;32m&#34;17&#34;[0m but got: [0;31m&#34;&#34;[0m">    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:92:44)
    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>

    <failure message="    at NightwatchAPI.&lt;anonymous&gt; (C:\Users\Veneren\DevMountain\kslProject\tests\challenge.js:92:44)">    at process._tickCallback (internal/process/next_tick.js:68:7)</failure>
    </testcase>
  

  

  
  </testsuite>
</testsuites>
